# Generated by Django 4.2.3 on 2023-07-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0004_tweet_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
