# Generated by Django 4.2.3 on 2023-07-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0007_profile_github_link_profile_instagram_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_link',
            new_name='facebook_link',
        ),
    ]
